---
- 
  name: Install Nginx and start it
  hosts: servers
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest 
    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Move index.html
      copy: 
        src: index.html
        dest: /var/www/html/index.html
        mode: '0755'
        remote_src: false

    - name: Enable Nginx service
      systemd:
        name: nginx
        daemon_reload: yes
        enabled: yes
        state: started