apiVersion: v1
kind: Pod
metadata:
  name: pod-blue
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "color"
      operator: "Equal"
      value: "red"
      effect: "NoSchedule"
